version: '3.8'
services:
  app:
    container_name: ${APP_CONTAINER}
    image: ${REGISTRY}/${APP_NAME}:${APP_VERSION}
    restart: unless-stopped
    tty: true
    environment:
        GO_ENV: ${GO_ENV}
        PORT: ${PORT}
        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        JWT_AUD: ${JWT_AUD}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_SSL: ${POSTGRES_SSL}
        POSTGRES_HOST_PROD: ${POSTGRES_HOST_PROD}
        POSTGRES_PORT_PROD: ${POSTGRES_PORT_PROD}
        POSTGRES_DB_PROD: ${POSTGRES_DB_PROD}
        POSTGRES_USER_PROD: ${POSTGRES_USER_PROD}
        POSTGRES_PASSWORD_PROD: ${POSTGRES_PASSWORD_PROD}
        POSTGRES_SSL_PROD: ${POSTGRES_SSL_PROD}
        OBJECT_STORAGE_REGION: ${OBJECT_STORAGE_REGION}
        OBJECT_STORAGE_ENDPOINT: ${OBJECT_STORAGE_ENDPOINT}
        OBJECT_STORAGE_BUCKET: ${OBJECT_STORAGE_BUCKET}
        OBJECT_STORAGE_ACCESS_KEY: ${OBJECT_STORAGE_ACCESS_KEY}
        OBJECT_STORAGE_SECRET_ACCESS_KEY: ${OBJECT_STORAGE_SECRET_ACCESS_KEY}
        OBJECT_STORAGE_ACCESS_FILE: ${OBJECT_STORAGE_ACCESS_FILE}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - digylabs-admin-pos-service

#Docker Networks
networks:
  digylabs-admin-pos-service:



